FROM python:3.10-slim
WORKDIR /app

COPY app.py /app/app.py
COPY requirements.txt /app/requirements.txt
COPY model.onnx /app/model.onnx

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
# CMD ["python", "app.py"]

RUN useradd -m justuser
USER justuser